language: go

go:
  - 1.13.x

before_install:
  - go get -v gopkg.in/alecthomas/kingpin.v2

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "g810-workspaces"
  skip_cleanup: true
  on:
    tags: true